version: '3.8'

services:
  web:
    build: my-flask-app:mutlistage
    ports:
      - "5000:5000"
    depends_on:
      - mydb

  mydb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw