version: '3.8'

services:
  web:
    build: .
    ports:
      - "7777:7777"  # Map port 7777 on host to port 7777 in the container
    environment:
      - REDIS_HOST=myredis
      - REDIS_PORT=6379
    depends_on:
      - myredis

  myredis:
    image: redis:alpine
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount custom nginx config
    ports:
      - "8080:7777"  # Expose Nginx on port 8080 on the host, it will proxy to Flask on port 7777
    depends_on:
      - web

volumes:
  redis_data:
